services:
  - type: web
    name: fastapi-app
    env: python
    plan: free
    branch: main  # o el nombre de la rama donde está tu código
    buildCommand: ""
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
